
INSERT INTO ur_instruction_dict(DICTID,NETTYPE,NETYPE,MANUFACTURE,VERSION,INSTRUCTION,PRIORITY,CREATETIME,CREATEUSER,MODITIME,MODIUSER,REMARK,ISTEMPLATE,DICTGROUP,GROUPPREFIX,GROUPSUFFIX
) SELECT '98',NETTYPE,NETYPE,MANUFACTURE,VERSION,'CNACLD_DT',PRIORITY,CREATETIME,CREATEUSER,MODITIME,MODIUSER,REMARK,ISTEMPLATE,DICTGROUP,GROUPPREFIX,GROUPSUFFIX
 FROM ur_instruction_dict WHERE  INSTRUCTION='CNACLD' AND NETYPE='4'
 
 INSERT INTO UR_INSTRUCTION_DICT_ITEM(DICTID,ITEMID,PRIORITY,ENGLISHNAME,CHINESENAME,PARAMFORMAT,PARAMTYPE,CREATETIME,CREATEUSER,MODITIME,MODIUSER,STATUS,REMARK,ISCORE,PARAMREMARK,IS_SORT
) SELECT '98',ITEMID,PRIORITY,ENGLISHNAME,CHINESENAME,PARAMFORMAT,PARAMTYPE,CREATETIME,CREATEUSER,MODITIME,MODIUSER,STATUS,REMARK,ISCORE,PARAMREMARK,IS_SORT
 FROM UR_INSTRUCTION_DICT_ITEM WHERE DICTID='99'
 
 
 INSERT INTO UR_INSTRUCTION_ITEM_VALUE(DICTID,ITEMID,CHINESEVAL,ENGLISHVAL,BUSILIST,CREATETIME,CREATEUSER,MODITIME,MODIUSER,STATUS,REMARK,VARIANTTYPE,EXTENTIONVALUE
) SELECT '98',ITEMID,CHINESEVAL,ENGLISHVAL,BUSILIST,CREATETIME,CREATEUSER,MODITIME,MODIUSER,STATUS,REMARK,VARIANTTYPE,EXTENTIONVALUE
 FROM UR_INSTRUCTION_ITEM_VALUE WHERE DICTID='99'
 
 /*操作映射*/
 INSERT INTO UR_OPERATION_MAP(DICTID,STANDARDOPERATION,PRODUCTIONMODE,INSTEMPLATE,INSCATEGORY,OPERATIONTYPE,INSTYPE,INSSEQUENCE,REMARK
) SELECT '111',STANDARDOPERATION,PRODUCTIONMODE,INSTEMPLATE,INSCATEGORY,OPERATIONTYPE,INSTYPE,INSSEQUENCE,REMARK
FROM UR_OPERATION_MAP WHERE DICTID='110'




/**视图**/
SELECT wm_concat(COLUMN_NAME) FROM User_Tab_Columns WHERE table_name='HW_ROAM_FW_DATA'

SELECT * FROM sys_busi_table_def WHERE table_name='HW_ROAM_FW_DATA'

INSERT INTO SYS_BUSI_COLUMN_DEF(REF_CLASS,ID,TABLE_DEF_ID,IS_PK,COLUMN_NAME,DISPLAY_NAME,STATUS,PARSE_ORDER,RENDER_ORDER,IS_BUSI_PK,CONTENT_LEN,IS_RES,RES_NAME) SELECT REF_CLASS,SYS_GUID(),'8a5983b358de26b10158fb7256b30174',IS_PK,COLUMN_NAME,DISPLAY_NAME,STATUS,PARSE_ORDER,RENDER_ORDER,IS_BUSI_PK,CONTENT_LEN,IS_RES,RES_NAME FROM SYS_BUSI_COLUMN_DEF WHERE table_def_id LIKE '%402882b44c967d56014c988174b50172%'

SELECT * FROM SYS_BUSI_COLUMN_DEF WHERE  table_def_id='402882b44c967d56014c988174b50172'FOR UPDATE

/**方案**/

SELECT * FROM ur_rule_instruction_param WHERE INSTRUCTIONCODE='202601040200001'
INSERT INTO ur_rule_instruction_param(INSTRUCTIONCODE,PARAMPROPERTY,PARAMTYPE,PARAMDICTID,PARAMITEMID,CHINESEVAL,ENGLISHVAL,CHANGENAME,CHECKLOGIC,RULEDESC,CREATETIME,CREATEUSER,MODITIME,MODIUSER,STATUS,REMARK,ARGS
) SELECT '202601040200002',PARAMPROPERTY,PARAMTYPE,PARAMDICTID,PARAMITEMID,CHINESEVAL,ENGLISHVAL,CHANGENAME,CHECKLOGIC,RULEDESC,CREATETIME,CREATEUSER,MODITIME,MODIUSER,STATUS,REMARK,ARGS FROM ur_rule_instruction_param WHERE INSTRUCTIONCODE='202601040200001'